// ===== 几何美学拼豆模板（程序化生成，行宽恒定）=====
const GEOM_TEMPLATES = {
  '几何美学': [
    { name:'🎯 同心圆环', grid: `....................\n.......PPPPPP.......\n.....PPVVVVVVPP.....\n....PVVVBBBBVVVP....\n...PVVBBBBBBBBVVP...\n..PVVBBGGGGGGBBVVP..\n..PVBBGGYYYYGGBBVP..\n.PVVBGGYYOOYYGGBVVP.\n.PVBBGYYOOOOYYGBBVP.\n.PVBBGYOORROOYGBBVP.\n.PVBBGYOORROOYGBBVP.\n.PVBBGYYOOOOYYGBBVP.\n.PVVBGGYYOOYYGGBVVP.\n..PVBBGGYYYYGGBBVP..\n..PVVBBGGGGGGBBVVP..\n...PVVBBBBBBBBVVP...\n....PVVVBBBBVVVP....\n.....PPVVVVVVPP.....\n.......PPPPPP.......\n....................` },
    { name:'🌈 彩虹渐变', grid: `RRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV\nRRRROOOYYYGGGBBBVVVV` },
    { name:'🌈 竖彩虹', grid: `CCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCC\nCCCCCCCCCCCCCCCCCCCC\nBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBB\nVVVVVVVVVVVVVVVVVVVV\nVVVVVVVVVVVVVVVVVVVV\nVVVVVVVVVVVVVVVVVVVV\nPPPPPPPPPPPPPPPPPPPP\nPPPPPPPPPPPPPPPPPPPP\nRRRRRRRRRRRRRRRRRRRR\nRRRRRRRRRRRRRRRRRRRR\nRRRRRRRRRRRRRRRRRRRR\nOOOOOOOOOOOOOOOOOOOO\nOOOOOOOOOOOOOOOOOOOO\nOOOOOOOOOOOOOOOOOOOO\nYYYYYYYYYYYYYYYYYYYY\nYYYYYYYYYYYYYYYYYYYY\nYYYYYYYYYYYYYYYYYYYY` },
    { name:'🌸 六瓣花', grid: `....................\n....................\n.............W......\n.....W......VP......\n.....VV....VV.......\n......V....pV.......\n......Vp...p........\n.......pp...........\n...............VV...\n.........YY.pppVVPW.\n.WPVVppp.YY.........\n...VV...............\n...........pp.......\n........p...pV......\n.......Vp....V......\n.......VV....VV.....\n......PV......W.....\n......W.............\n....................\n....................` },
    { name:'☯️ 太极', grid: `....................\n.........WW.........\n......WWWWWWWW......\n....WWWWWWWWWWWW....\n...WWWWWWWWWWWWWW...\n...WWWWWWWWWWWWWW...\n..WWWWWWWWWWWWWWWW..\n..WWWWWWWWWWWkkkkk..\n..WWWWWWWWWWkkkkkk..\n.WWWWWWWWWWkkkkkkkk.\n.WWWWWWWWkkkkkkkkkk.\n..WWWWWWkkkkkkkkkk..\n..WWWWWkkkkkkkkkkk..\n..kkkkkkkkkkkkkkkk..\n...kkkkkkkkkkkkkk...\n...kkkkkkkkkkkkkk...\n....kkkkkkkkkkkk....\n......kkkkkkkk......\n.........kk.........\n....................` },
  ]
,
  '炫彩图案': [
    { name:'💎 宝石', grid: `....................\n.........kk.........\n........kWWk........\n.......kWWWWk.......\n......kYWWWWYk......\n.....kYYYppYYYk.....\n....kYYYppppYYYk....\n...kYYYppVVppYYYk...\n..kYYYppVVVVppYYYk..\n.kYYYppVVVVVVppYYYk.\n.kYYYppVVVVVVppYYYk.\n..kYYYppVVVVppYYYk..\n...kYYYppVVppYYYk...\n....kYYYppppYYYk....\n.....kYYYppYYYk.....\n......kYYYYYYk......\n.......kYYYYk.......\n........kYYk........\n.........kk.........\n....................` },
    { name:'✨ 八芒星', grid: `....................\n......Y......Y......\n....................\n.......Y....Y.......\n.......Y....Y.......\n........Y..Y........\n.Y......Y..Y......Y.\n...YY..........YY...\n.....YY..YY..YY.....\n........YJJY........\n........YJJY........\n.....YY..YY..YY.....\n...YY..........YY...\n.Y......Y..Y......Y.\n........Y..Y........\n.......Y....Y.......\n.......Y....Y.......\n....................\n......Y......Y......\n....................` },
    { name:'🌀 螺旋', grid: `....................\n......BBBBBBBB......\n.....BBBBGGGGGG.....\n...VBBBBGGGGGGGGG...\n...VBBBGGGGGGGGGG...\n..VBBBGGGGYYYYYYGG..\n.VVBBBGGGYYYYYYYYGG.\n.VVBBBGGYYYOOOYYYYG.\n.VVBBBGGYYOOOOOYYYY.\n.VVVBBBGGYRROOOOYYY.\n.VVVBBBBGGVRROOOYYY.\n.VVVVBBBBBVVRROOOYY.\n.RVVVVBBBVVVRROOOYY.\n.RRVVVVVVVVRRROOOYY.\n..RRVVVVVVRRRROOOY..\n...RRRRRRRRRROOOY...\n...RRRRRRRRROOOOY...\n.....RRRRRROOOO.....\n......OOOOOOOO......\n....................` },
    { name:'🕉️ 万花筒', grid: `....................\n......CPMOUBVY......\n.....VYPMUBYCCP.....\n...OUVYPOBVCCMOOO...\n...OUVCPOBVCMOOUU...\n..POOBYPOBCMUUBVVV..\n.YCMOUVCOVPUBVYCYYC.\n.VCCMUBYMVOBYCPPPPP.\n.BYCCMUBCBUCMOOOOMM.\n.UBVVCPOUPPBVVBBBUO.\n.OUBBBVVBPPUOPCVVBU.\n.MMOOOOMCUBCBUMCCYB.\n.PPPPPCYBOVMYBUMCCV.\n.CYYCYVBUPVOCVUOMCY.\n..VVVBUUMCBOPYBOOP..\n...UUOOMCVBOPCVUO...\n...OOOMCCVBOPYVUO...\n.....PCCYBUMPYV.....\n......YVBUOMPC......\n....................` },
    { name:'❄️ 雪花', grid: `....................\n....................\n....................\n....................\n.........BB.........\n....................\n...CCB...BB...BCC...\n.....C........C.....\n......BC....CB......\n....................\n....................\n......BC....CB......\n.....C........C.....\n...CCB...BB...BCC...\n....................\n.........BB.........\n....................\n....................\n....................\n....................` },
    { name:'🌌 星云', grid: `....................\n......CCCCCCCC......\n.....CCppppppCC.....\n...JCCppppppppCCJ...\n...CCpppYYYYpppCC...\n..CCCppYVVVVYppCCC..\n.JCCppYVppppVYppCCJ.\n.CCpppVVppppVVpppCC.\n.CCppVVppRRppVVppCC.\n.CCppVVppRRppVVppCC.\n.CppYVppRRRRppVYppC.\n.CppYVppRppRppVYppC.\n.CppYYppppppppYYppC.\n.CCppYYVVVVVVYYppCC.\n..CpppYYVVVVYYpppC..\n...CppppppppppppC...\n...CCCppppppppCCC...\n.....CCCCCCCCCC.....\n......CCCCCCCC......\n....................` },
    { name:'🪐 星球', grid: `....................\n....................\n....................\n....................\n.......bbbbbb.......\n......bbbbbbbb......\n.J...bbbbbbbbbb...J.\n.J..bbbbbWWbbbbb..J.\n.J..bbbbWWWWbbbb..J.\n.J..CCCWWWWWWCCC..J.\n.J..CCCWWWWWWCCC..J.\n.J..BBBBWWWWBBBB..J.\n.J..BBBBBWWBBBBB..J.\n.J...BBBBBBBBBB...J.\n......BBBBBBBB......\n.......BBBBBB.......\n....................\n....................\n....................\n....................` },
    { name:'🌄 极光', grid: `KKKKKKppppKKKKKKKppp\npKKKKppppppKKKKKpppp\nppKKpppVVVpppKKppVVV\nVpppppVVVVVpppppVVVV\nVVppVVVCCCVVpppVVCCC\nCVVVVVCCCCCVVVVVCCCC\nCCVVVCCBKBCCVVVCCBKK\nBCCCCCKKKKBCCCCCBKKK\nKBCCCKKKKKKBCCCBKKKK\nKKBBKKKKKKKKKBBKKKKK\nKKKKKKKKKKKKKKKKKKKK\nKKKKKKKKKKKKKKKKKKKK\nKKKKKKKKKKKKKKKKKKKK\nKKKKKKKKKKKKKKKKKKKK\nKKKKKKKKKKKKKKKKKKKK\nKKKKKKKKKKKKKKKKKKKK\nKKKKKKKKKKKKKKKKKKKK\nKKKKKKKKKKKKKKKKKKKK\nKKKKKKKKKKKKKKKKKKKK\nKKKKKKKKKKKKKKKKKKKK` },
    { name:'🌊 海浪', grid: `UUAAUUUUUUAAUUUUUUUA\nUUUUUUCCUUUUUUCCCUUU\nUUUUUCCCCUUUUUCCCCUU\nCUUUCCCCCCUUUCCCCCUU\nCCUCCCBBCCCUCCCBCCCU\nCCCCCBBBBCCCCCBBBCCC\nBCCCCBBBBCCCCBBBBBCC\nBCCCBBBBBBCCCBBBBBBC\nBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBB\nBBBBBBAABBBBBBAAABBB\nBBBBBAAAABBBBBAAAABB\nABBBAAAAAABBBAAAAABB\nAABAAAUUAAABAAAUAAAB\nAAAAAUUUUAAAAAUUUAAA\nUAAAAUUUUAAAAUUUUUAA\nUAAAUUUUUUAAAUUUUUUA\nUUUUUUCCUUUUUUUCCUUU` },
    { name:'🏔️ 山与太阳', grid: `BBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBB\nBBBBBBBBBBBBBBBBBBBB\nBBBBBJJBBBBBBBBBBBBB\nBBBBJJJBBBBBBBBBBBBB\nBBBBJJJBBBBBBBBBBBBB\nBBBBBBBBBBWBBBBBBBBB\nCCCCCCCCCWGWCCCCCCCC\nUUUUUggUGGGGGUUUUUUU\nUUUUgggGGGGGGGUUUUUU\nUUUUggGGGGGGGGGUUUUU\nUUUggGGGGGGGGGGGUUUU\nUUggGGGGGGGGGGGGGUUU\nUggGGGGGGGGGGGGGGGUU\nggGGGGGGGGGGGGGGGGGU\ngGGGGGGGGGGGGGGGGGGG\nGGGGGGGGGGGGGGGGGGGG\nGGGGGGGGGGGGGGGGGGGG` },
  ]
};